version: 0.2

phases:
  install:
    commands:
      - export DEBIAN_FRONTEND=noninteractive
      # Install nodejs and npm
      - curl -sL https://deb.nodesource.com/setup_8.x | bash -
      - apt-get install nodejs -y
      - node --version
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run $ENVIRONMENT
artifacts:
  files:
    - '**/*'
